### ISSUE TITLE
Grafana failing up 

### ISSUE THREAD

**Issue by byteshiva** [samuelebistoletti/docker-statsd-influxdb-grafana#1]
run_grafana
=> Starting Grafana ...
[FAIL] Starting Grafana Server: failed!

**Comment by samuelebistoletti** [comment]
Grafana should be launched by supervisord at container boot. I tried to rebuild the image and I was not able to reproduce this problem: if I try to launch "run_grafana" executable i get this.

 => Starting Grafana ...
[ ok ] Starting Grafana Server:[....] Already running..
