### ISSUE TITLE
How to add persistent storage?

### ISSUE THREAD

**Issue by amareto** [samuelebistoletti/docker-statsd-influxdb-grafana#13]
Is there a way to add persistent storage to save db and conf?

**Comment by samuelebistoletti** [comment]
Hi,
I tested the container against persisence, all data should be kept if you stop the container and start it again, using Docker commands in README -

To stop the container launch:

docker stop docker-statsd-influxdb-grafana

To start the container again launch:

docker start docker-statsd-influxdb-grafana

**Comment by ssbarnea** [comment]
I am not sure this answered the question. Container persistence is achieve my mounting data volumes but I see not data volume documented in container specification, at all.

Example: unifi docker container uses /config for persisting configuraiton, jenkins official containers rely on /var/jenkins_home for data persistance.

Also as a rule these containers are supposed to be succesfully start with an empty data volume, and they would populate them with all data that needs to be persisted. A container can be destroyed at any time and could be spawned on a totally different manchine but the data volume is supposed to be remounted.
