### ISSUE TITLE
Grafana 4.1.1

### ISSUE THREAD

**Issue by rashtisouciance** [samuelebistoletti/docker-statsd-influxdb-grafana#14]
Hi,

Any chance you can update your Dockerfile to publish an image with grafana 4.1.1 which contains alerting now as well? I tried to build based on your dockerfile but it seems to be dependent on folders on the host.

Thanks.

**Comment by samuelebistoletti** [comment]
Hi,
I released version 2.0.0 of this Docker image a few minutes ago. I included Grafana 4.1.1, you can find the full changelog here: 

https://github.com/samuelebistoletti/docker-statsd-influxdb-grafana/blob/master/CHANGELOG.md
