### ISSUE TITLE
Image creation fails when creating database to influx

### ISSUE THREAD

**Issue by kattelus** [samuelebistoletti/docker-statsd-influxdb-grafana#2]
From docker hub log

`=> Creating database: data
[91m [0m[91m [0m[91m%[0m[91m [0m[91mT[0m[91mo[0m[91mt[0m[91ma[0m[91ml[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m%[0m[91m [0m[91mR[0m[91me[0m[91mc[0m[91me[0m[91mi[0m[91mv[0m[91me[0m[91md[0m[91m [0m[91m%[0m[91m [0m[91mX[0m[91mf[0m[91me[0m[91mr[0m[91md[0m[91m [0m[91m [0m[91mA[0m[91mv[0m[91me[0m[91mr[0m[91ma[0m[91mg[0m[91me[0m[91m [0m[91mS[0m[91mp[0m[91me[0m[91me[0m[91md[0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91mC[0m[91mu[0m[91mr[0m[91mr[0m[91me[0m[91mn[0m[91mt[0m[91m
[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91mD[0m[91ml[0m[91mo[0m[91ma[0m[91md[0m[91m [0m[91m [0m[91mU[0m[91mp[0m[91ml[0m[91mo[0m[91ma[0m[91md[0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mo[0m[91mt[0m[91ma[0m[91ml[0m[91m [0m[91m [0m[91m [0m[91mS[0m[91mp[0m[91me[0m[91mn[0m[91mt[0m[91m [0m[91m [0m[91m [0m[91m [0m[91mL[0m[91me[0m[91mf[0m[91mt[0m[91m [0m[91m [0m[91mS[0m[91mp[0m[91me[0m[91me[0m[91md[0m[91m
[0m[91m
[0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m   0     0      0      0 --:--:-- --:--:-- --:--:--     0[0m[91m[http] 2016/02/23 10:17:01 ::1 - root [23/Feb/2016:10:17:01 +0000] GET /query?p=%5BREDACTED%5D&q=CREATE+DATABASE+data&u=root HTTP/1.1 400 83 - curl/7.38.0 9402a324-da16-11e5-8006-000000000000 194.374µs
[0m[91m
[0m[91m1[0m[91m0[0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m8[0m[91m3[0m[91m [0m[91m [0m[91m1[0m[91m0[0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m8[0m[91m3[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m4[0m[91m2[0m[91m1[0m[91m9[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m [0m[91m4[0m[91m3[0m[91m6[0m[91m8[0m[91m
[0m{"error":"error parsing query: found DATA, expected identifier at line 1, char 17"}
=> Creating User for database: data
[91m [0m[91m [0m[91m%[0m[91m [0m[91mT[0m[91mo[0m[91mt[0m[91ma[0m[91ml[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m%[0m[91m [0m[91mR[0m[91me[0m[91mc[0m[91me[0m[91mi[0m[91mv[0m[91me[0m[91md[0m[91m [0m[91m%[0m[91m [0m[91mX[0m[91mf[0m[91me[0m[91mr[0m[91md[0m[91m [0m[91m [0m[91mA[0m[91mv[0m[91me[0m[91mr[0m[91ma[0m[91mg[0m[91me[0m[91m [0m[91mS[0m[91mp[0m[91me[0m[91me[0m[91md[0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91mC[0m[91mu[0m[91mr[0m[91mr[0m[91me[0m[91mn[0m[91mt[0m[91m
[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91mD[0m[91ml[0m[91mo[0m[91mad  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[0m{"error":"error parsing query: found DATA, expected identifier at line 1, char 13"}[91m[http] 2016/02/23 10:17:01 ::1 - root [23/Feb/2016:10:17:01 +0000] GET /query?p=%5BREDACTED%5D&q=CREATE+USER+data+WITH+PASSWORD+%27data%27&u=root HTTP/1.1 400 83 - curl/7.38.0 940c8493-da16-11e5-8007-000000000000 116.354µs

100    83  100    83    0     0   3003      0 --:--:-- --:--:-- --:--:--  3074
[0m[91m [0m[91m [0m[91m%[0m[91m [0m[91mT[0m[91mo[0m[91mt[0m[91ma[0m[91ml[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m%[0m[91m [0m[91mR[0m[91me[0m[91mc[0m[91me[0m[91mi[0m[91mv[0m[91me[0m[91md[0m[91m [0m[91m%[0m[91m [0m[91mX[0m[91mf[0m[91me[0m[91mr[0m[91md[0m[91m [0m[91m [0m[91mA[0m[91mv[0m[91me[0m[91mr[0m[91ma[0m[91mg[0m[91me[0m[91m [0m[91mS[0m[91mp[0m[91me[0m[91me[0m[91md[0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mi[0m[91mm[0m[91me[0m[91m [0m[91m [0m[91mC[0m[91mu[0m[91mr[0m[91mr[0m[91me[0m[91mn[0m[91mt[0m[91m
[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91mD[0m[91ml[0m[91mo[0m[91ma[0m[91md[0m[91m [0m[91m [0m[91mU[0m[91mp[0m[91ml[0m[91mo[0m[91ma[0m[91md[0m[91m [0m[91m [0m[91m [0m[91mT[0m[91mo[0m[91mt[0m[91ma[0m[91ml[0m[91m [0m[91m [0m[91m [0m[91mS[0m[91mp[0m[91me[0m[91mn[0m[91mt[0m[91m [0m[91m [0m[91m [0m[91m [0m[91mL[0m[91me[0m[91mf[0m[91mt[0m[91m [0m[91m [0m[91mS[0m[91mp[0m[91me[0m[91me[0m[91md[0m[91m
[0m[91m
[0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m[http] 2016/02/23 10:17:01 ::1 - root [23/Feb/2016:10:17:01 +0000] GET /query?p=%5BREDACTED%5D&q=GRANT+ALL+ON+data+TO+data&u=root HTTP/1.1 400 83 - curl/7.38.0 94125e79-da16-11e5-8008-000000000000 84.019µs
[0m[91m
[0m[91m1[0m[91m0[0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m8[0m[91m3[0m[91m [0m[91m [0m[91m1[0m[91m0[0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m8[0m[91m3[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m [0m[91m [0m[91m3[0m[91m7[0m[91m6[0m[91m3[0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m [0m[91m0[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m:[0m[91m-[0m[91m-[0m[91m [0m[91m [0m[91m3[0m[91m9[0m[91m5[0m[91m2[0m[91m
[0m{"error":"error parsing query: found DATA, expected identifier at line 1, char 14"}`

**Comment by kattelus** [comment]
It seems that influx consider queries with plain data word in query invalid.

Tried same queries through browser ui by replacing plain data with "data" ant there those created database fine with that minor change.

**Comment by samuelebistoletti** [comment]
I'm already working on that, unfortunately the new release of InfluxDB refuses to create a database named "data". Fix is coming next monday

**Comment by samuelebistoletti** [comment]
Exactly as you said

**Comment by samuelebistoletti** [comment]
Fixed in the last version
