### ISSUE TITLE
User defined tags for metrics

### ISSUE THREAD

**Issue by mapruyas** [samuelebistoletti/docker-statsd-influxdb-grafana#26]
Is there any configuration needed to get metrics with user defined tags in influxDB?
I'm sending stuff like this

prefix.metric.test:1|c|#foo:bar

and the measurement in influx contains time host metric_type value but no tags

**Comment by zahiar** [comment]
Those tags are using Datadog's format (https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/). I had a similar issue until I enabled an option in Telegraf's config to support parsing tags in Datadog's format.

I've created a pull request for this change here: https://github.com/samuelebistoletti/docker-statsd-influxdb-grafana/pull/30
