### ISSUE TITLE
How enabled influxdb graphite port 2003?

### ISSUE THREAD

**Issue by andreluizf** [samuelebistoletti/docker-statsd-influxdb-grafana#33]
I am trying to generate a report from jmeter but I have paired this error.

ERROR o.a.j.v.b.g.TextGraphiteMetricsSender: Error writing to Graphite: Conexão recusada (Connection refused)

![image](https://user-images.githubusercontent.com/3831600/57874203-68721080-77e6-11e9-861b-820e1d185d64.png)

**Comment by zferenczik** [comment]
InfluxDB provided by default for a good reason: https://www.influxdata.com/blog/influxdb-outperforms-graphite-in-time-series-data-metrics-benchmark/

Works fine with the latest JMeter version 5.4.1.
