### ISSUE TITLE
install plugin grafana 

### ISSUE THREAD

**Issue by runtimevic** [samuelebistoletti/docker-statsd-influxdb-grafana#36]
hello, 

I want to install a plugin grafana in this container as it should?
example: grafana-piechart-panel
Regards, Victor.

**Comment by runtimevic** [comment]
this is what i am testing:
docker run -d \
-p 3000:3000 \
--name=docker-statsd-influxdb-grafana \
-e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource" \
samuelebistoletti/docker-statsd-influxdb-grafana

**Comment by runtimevic** [comment]
docker run -d \
-p 3000:3000 \
--name=docker-statsd-influxdb-grafana \
-e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource" \
samuelebistoletti/docker-statsd-influxdb-grafana

**Comment by runtimevic** [comment]
docker run -d \
-p 3000:3000 \
--name=grafana \
-e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource" \
grafana/grafana

**Comment by runtimevic** [comment]
conseguido:
docker exec -it docker-statsd-influxdb-grafana grafana-cli plugins install grafana-piechart-panel
por si alguien le interesa esto es como realizarlo

**Comment by samuelebistoletti** [comment]
Hi, should also be possible to provision the plugin from outside: https://grafana.com/docs/grafana/latest/administration/provisioning/
