### ISSUE TITLE
[DOC] Database outside docker

### ISSUE THREAD

**Issue by pieterzen** [samuelebistoletti/docker-statsd-influxdb-grafana#40]
More a documentation issue than anything, but I thought I'd share it over here. 
I installed my docker following the provided instructions and all was fine. Then I upgraded the docker, and low and behold (and I should've realised this myself) the database was gone. 

The instruction `docker run` are lacking the `-v` step:
-v /volume1/<your local directory>/influxdb/:/var/lib/influxdb
This will use your local drive as database storage. 

Since mr. Bistoletti kindly created the docker with a pre-installed database this option unfortunately doesn't work out of the box. It will stop the influx from loading. 

The way I resolved this was to first start the newly created docker (so you only need to do this on first run) without the `-v` flag. Then copy the database to the local environment with the following command:
`docker cp docker-statsd-influxdb-grafana:/var/lib/influxdb /volume1/<your local directory>/influxdb/`

For others running into this issue, here are the commands I use to start my docker:
```
docker stop docker-statsd-influxdb-grafana
docker pull samuelebistoletti/docker-statsd-influxdb-grafana:latest
docker rm docker-statsd-influxdb-grafana
docker run --ulimit nofile=66000:66000 -d --name docker-statsd-influxdb-grafana \
  -p 3003:3003 -p 3004:8888 -p 8086:8086 -p 8125:8125/udp \
  -v /volume1/SmartHome/influxdb/:/var/lib/influxdb \
  --restart=unless-stopped samuelebistoletti/docker-statsd-influxdb-grafana:latest
```

**Comment by pieterzen** [comment]
I've been testing with this, but apparently more needs to be done to make this work. I've had to give access to the external influxdb directory. I also need to find where Grafana stores it's dashboards. Haven't been able to do so as of yet...

**Comment by pieterzen** [comment]
I followed all documentation, but I'm apparently not capable of getting this to work. According to sources mapping /lib/influxdb to the external directory doesn't work for this docker :(

**Comment by samuelebistoletti** [comment]
With the new version I released this evening that should be easy, please check on that.

Thanks
