### ISSUE TITLE
grafana.ini

### ISSUE THREAD

**Issue by afreisinger** [samuelebistoletti/docker-statsd-influxdb-grafana#46]
Is the content of the grafana.ini file correct? By default mysql is used. Not postgress config is set.

**Comment by vincentdh** [comment]
It's using the [grafana/grafana.env](https://github.com/samuelebistoletti/docker-statsd-influxdb-grafana/blob/66adf2a10d985e71a7d47b5c5fcf246629303d76/grafana/grafana.env) file. The [Grafana section in the README.MD](https://github.com/samuelebistoletti/docker-statsd-influxdb-grafana/blob/66adf2a10d985e71a7d47b5c5fcf246629303d76/README.md#grafana) should probably be modified to clarify it...

Also, the port is not 3003, but 3000 and the default username/password is admin/admin and not root/root.

**Comment by afreisinger** [comment]
Thanks !
