### ISSUE TITLE
Error when choosing InfluxDB as a source in Grafana using direct access

### ISSUE THREAD

**Issue by dragan-vujovic** [samuelebistoletti/docker-statsd-influxdb-grafana#7]
Choosing InfluxDB as a source and configuring it according to the guide fails on testing connection.
When proxy access is chosen connection is successful. If this is intended connection type the guide should be updated.

**Comment by stantonk** [comment]
I'm experiencing the same. Did a fresh docker pull of the image today.

**Comment by samuelebistoletti** [comment]
Hi,
sorry but I was not able to reproduce this error. Please, try with the new 2.0.0 release, lot of things have changed.
