### ISSUE TITLE
InfluxDB web interface not protected

### ISSUE THREAD

**Issue by dragan-vujovic** [samuelebistoletti/docker-statsd-influxdb-grafana#8]
Although the guide says that the access to InfluxDB web interface is protected with password, the intefrace loads without any authentication.

**Comment by samuelebistoletti** [comment]
I'm sorry but that part of the README is unclear, I will fix that asap. Username, password and port are referred to the database, not to the web interface.

**Comment by coderberry** [comment]
@samuelebistoletti I still find that this is an issue. Do you know of a solution to protect the InfluxDB web interface?
