### ISSUE TITLE
How to add plugins?

### ISSUE THREAD

**Issue by tomsoft1** [samuelebistoletti/docker-statsd-influxdb-grafana#9]
I've tryed the following approach:

Connect to the docker container using docker exec with a bash shell

`grafana-cli plugins install grafana-piechart-panel`

And then restart the grafan service but the piechart is still not here?

**Comment by samuelebistoletti** [comment]
Hi,
I tried to install the same plugin, and it was successfull. Please, try with the new 2.0.0 release with Grafana 4.1.1.

# Install plugin
grafana-cli plugins install grafana-piechart-panel

# Restart service
/etc/init.d/grafana-server restart

![screen](https://cloud.githubusercontent.com/assets/4482391/22396999/dc018c84-e566-11e6-9455-270833ed384e.png)
